export const CLUBS = [
  { id: 'CK2', name: '建中青年刊物社', capacity: 250 },
  { id: 'CK3', name: '樂旗隊', capacity: 21000 },
  { id: 'A01', name: '科學研習社', capacity: null },
  { id: 'A02', name: '生物研究社', capacity: 1500 },
  { id: 'A03', name: '物理研究社', capacity: 700 },
  { id: 'A05', name: '天文社', capacity: 1000 },
  { id: 'A06', name: '數學社', capacity: 1000 },
  { id: 'A07', name: '電子計算機研習社', capacity: 300 },
  { id: 'A08', name: '資訊社', capacity: 500 },
  { id: 'A09', name: '國學暨人文社會學術研究社', capacity: null },
  { id: 'A10', name: '辯論社', capacity: null },
  { id: 'A13', name: '日本文化研究社', capacity: 500 },
  { id: 'A16', name: '講演社', capacity: 700 },
  { id: 'A16', name: '投資理財社', capacity: null },
  { id: 'A17', name: '電影研習社', capacity: null },
  { id: 'A20', name: '卡牌研究社', capacity: 500 },
  { id: 'A21', name: '軍武社', capacity: 500 },
  { id: 'A22', name: '小說創作研究社', capacity: null },
  { id: 'A25', name: '英文辯論社', capacity: 1000 },
  { id: 'A28', name: '物理辯論社', capacity: 750 },
  { id: 'A29', name: '建中創客社', capacity: 1500 },
  { id: 'A32', name: '建中機器人研究校隊暨社團', capacity: 8000 },
  { id: 'A33', name: 'Minecraft 邏輯研究社', capacity: null },
  { id: 'A34', name: '建中模擬聯合國', capacity: null },
  { id: 'A35', name: '世界地理探索社', capacity: null },
  { id: 'A36', name: '韓國文化研究社', capacity: null },
  { id: 'A37', name: '人工智慧研究社', capacity: null },
  { id: 'B01', name: '熱舞社', capacity: 4500 },
  { id: 'B05', name: '橋藝社', capacity: 500 },
  { id: 'B06', name: '象棋社', capacity: null },
  { id: 'B07', name: '圍棋社', capacity: 500 },
  { id: 'B08', name: '魔術社', capacity: 1000 },
  { id: 'B09', name: '美術社', capacity: 150 },
  { id: 'B10', name: '攝影社', capacity: 500 },
  { id: 'B11', name: '大眾傳播社', capacity: 1000 },
  { id: 'B12', name: '口技研究社', capacity: 1000 },
  { id: 'B13', name: '美食社', capacity: 1200 },
  { id: 'B14', name: '魔術方塊社', capacity: 500 },
  { id: 'B15', name: '桌上遊戲社', capacity: null },
  { id: 'B17', name: '模型動畫社', capacity: 500 },
  { id: 'B20', name: '漫畫插畫研究社', capacity: 500 },
  { id: 'B21', name: '表演藝術社', capacity: 500 },
  { id: 'B22', name: '烘焙社', capacity: 500 },
  { id: 'C01', name: '信望愛社', capacity: null },
  { id: 'C04', name: '聖經真理研習社', capacity: null },
  { id: 'C06', name: '尸外探索社', capacity: null },
  { id: 'C07', name: '駝鈴康輔社', capacity: null },
  { id: 'D01', name: '爵士音樂社', capacity: 2000 },
  { id: 'D02', name: '熱門音樂社', capacity: 2500 },
  { id: 'D03', name: '流行音樂社', capacity: 1000 },
  { id: 'D04', name: '另類音樂創作社', capacity: 2600 },
  { id: 'D05', name: '民謠吉他社', capacity: 1800 },
  { id: 'D06', name: '古典吉他社', capacity: 1500 },
  { id: 'D07', name: '管弦樂社', capacity: 5000 },
  { id: 'D08', name: '口琴社', capacity: 500 },
  { id: 'D09', name: '國樂社', capacity: 1000 },
  { id: 'D10', name: '合唱團', capacity: 500 },
  { id: 'D11', name: '嘻哈音樂研究社', capacity: 750 },
  { id: 'E02', name: '技擊社', capacity: 500 },
  { id: 'E03', name: '劍道社', capacity: 500 },
  { id: 'E04', name: '棒球社', capacity: 2000 },
  { id: 'E05', name: '游泳健身社', capacity: null },
  { id: 'E07', name: '桌球社', capacity: 400 },
  { id: 'E08', name: '羽球社', capacity: 1000 },
  { id: 'E09', name: '網球社', capacity: 1000 },
  { id: 'E10', name: '足球社', capacity: null },
  { id: 'E12', name: '排球社', capacity: 1000 },
  { id: 'F16', name: '音樂遊戲社', capacity: 500 },
  { id: 'Test', name: '測試社團', capacity: null },
]

export function getClubById(id) {
  return CLUBS.find(club => club.id === id)
}

export function getClubName(id) {
  const club = getClubById(id)
  return club ? club.name : ''
}
